---
- name: hello world
  hosts: localhost
  connection: local
  vars:
    vcenter_hostname: portal.vc.opentlc.com
    vcenter_username: sandbox-7gdj2@vc.opentlc.com
    vcenter_password: e431vm9:Y7i3
#    _instance_name: "{{ _instance.name }}{{ _index+1 if _instance.count|d(1)|int > 1 }}"
    _instance_userdata: |-
      cloud-config

  tasks:


  - name: Create a virtual machine on given ESXi hostname
    community.vmware.vmware_guest:
      state: present 
      folder: /Workloads/sandbox-7gdj2/
      template: 'rhel8_tmpl'
      name: test_vm_0005
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: SDDC-Datacenter
      cluster: Cluster-1
      networks:
      - name: segment-sandbox-7gdj2 
        device_type: vmxnet3
        start_connected: True
      advanced_settings:
        - key: "guestinfo.metadata"
          value: ""
        - key: "guestinfo.metadata.encoding"
          value: "base64"
        - key: "guestinfo.userdata"
          value: "{{ _instance_userdata | b64encode }}"
        - key: "guestinfo.userdata.encoding"
          value: "base64"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 600
    delegate_to: localhost
    register: deploy_vm
