---
- name: Perform some basic configurtion tasks on new VM
  hosts: all
  vars_files: vars/all.yml
  vars:
    _rhn_account_rhailsto:  "{{ _rhn_un }}"
    _rhn_password_rhailsto: "{{ _rhn_pw }}"
    dns_domain: 'cba.internal'

  tasks:

  - name : "Set the hostname as per inventory {{ inventory_hostname }}"
    ansible.builtin.hostname:
      name: "{{ inventory_hostname_short }}.{{ dns_domain }}"
      use: systemd

  - name: Register as user (rhn_user) with password (somepass) and auto-subscribe to available content.
    community.general.redhat_subscription:
      state: present
      username: "{{ _rhn_account_rhailsto }}" 
      password: "{{ _rhn_password_rhailsto }}" 
      auto_attach: true

- name: Update Crypto Policy
  hosts: all
  gather_facts: False
  collections:
    - redhat.rhel_system_roles
  tasks:
  - name: Configure crypto policies
    import_role:
      name: crypto_policies
    vars:
      - crypto_policies_policy: FUTURE
      - crypto_policies_reboot_ok: true
