---
- name: hello world
  hosts: localhost
  connection: local
  vars_files: vars/all.yml
  vars:
    vcenter_hostname: "{{ _vcenter_hostname }}"
    vcenter_username: "{{ _vcenter_username }}" 
    vcenter_password: "{{ _vcenter_password }}" 
    _instance_userdata: |-
      cloud-config
    _instance_name: "{{ survey_name | default('test_vm_0007') }}"

  tasks:


  - name: Create a virtual machine on given ESXi hostname
    community.vmware.vmware_guest:
      state: present
      folder: /Workloads/sandbox-7gdj2/
      template: 'rhel8_tmpl'
      name: test_vm_0007
      cluster: Cluster-1
      datacenter: SDDC-Datacenter
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      networks:
      - name: segment-sandbox-7gdj2 
        device_type: vmxnet3
        start_connected: True
      advanced_settings:
        - key: "guestinfo.metadata"
          value: ""
        - key: "guestinfo.metadata.encoding"
          value: "base64"
        - key: "guestinfo.userdata"
          value: "{{ _instance_userdata | b64encode }}"
        - key: "guestinfo.userdata.encoding"
          value: "base64"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 600
    delegate_to: localhost
    register: deploy_vm
